### ISSUE TITLE
image_scr가 비어있는 경우

### ISSUE THREAD

**Issue by uyt8989** [IsThisAd/IsThisAd#25]
https://blog.naver.com/serry222/222879021415

환주씨가 보내주신 data1.csv에서 해당 링크가 image_src가 비어있습니다.

**Comment by JJHWAN** [comment]
네이버 블로그의 형식의 차이로 발생하던 문제였습니다. 
현재 사용자들이 주로 사용하는 스마트 에디터, 기존의 스마터 에디터 3.0의 차이로 예외처리를 추가해서 이미지를 제공하도록 했습니다
