### ISSUE TITLE
이미지 크롤링이 끝까지 되지 않는 경우

### ISSUE THREAD

**Issue by uyt8989** [IsThisAd/IsThisAd#26]
https://blog.naver.com/djpinky/222886035851

OCR 해야 하는 타겟 이미지가 포스팅에 존재함에도 불구하고 그냥 음식 사진만 크롤링되는 경우가 있습니다.

**Comment by JJHWAN** [comment]
#28 이슈랑 같은 결의 이슈로 보이니 닫겠습니다

**Comment by JJHWAN** [comment]
@uyt8989  다른 링크 있나요? ㅎㅎ

**Comment by uyt8989** [comment]
@JJHWAN 죄송합니다 제가 착각했네요 여깁니다 https://blog.naver.com/azone_01/222889903154

**Comment by uyt8989** [comment]
https://blog.naver.com/cjsqhtmf/222886247233 추가입니다

**Comment by JJHWAN** [comment]
아마 네이버 스마트 에디터 버전 혹은 사용 유무 차이 같은데 좀 더 조사해보겠습니다

**Comment by JJHWAN** [comment]
> https://blog.naver.com/cjsqhtmf/222886247233 추가입니다

<img class="se-inline-image-resource egjs-visible" src="https://xn--939au0g4vj8sq.net/_sp/wg.php?ctf=OTgwN3wzNDU4ODE=" alt="" style="max-width: 410px">

해당 댓글의 블로그는 inline 형식으로 이미지를 사용하고 있는 걸 발견

**Comment by JJHWAN** [comment]
> @JJHWAN 죄송합니다 제가 착각했네요 여깁니다 https://blog.naver.com/azone_01/222889903154

해당 댓글의 블로그는 이미지 대용으로 스티커를 사용중
