### ISSUE TITLE
OCR 타겟 이미지가 스티커로 들어가있는 경우

### ISSUE THREAD

**Issue by uyt8989** [IsThisAd/IsThisAd#28]
https://blog.naver.com/psunhea1029/222884070974

이런 경우처럼 그냥 이미지가 아니라 네이버에서 제공하는 스티커로 들어있는 경우가 있습니다.
URL 크롤링이 안됩니다.

**Comment by uyt8989** [comment]
https://blog.naver.com/jang6634/222886691881

**Comment by uyt8989** [comment]
https://blog.naver.com/djpinky/222886035851

**Comment by JJHWAN** [comment]
추가했습니다.
